# Generated by Django 3.2.16 on 2022-12-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=50)),
                ('stuemail', models.EmailField(max_length=254)),
                ('stuphone', models.IntegerField()),
            ],
        ),
    ]
